In [2]:
import selenium
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

## 무한 스크롤 + 제목, 링크 수집 => 수집한 링크 하나씩 접속하면서 데이터 수집

In [3]:
driver = webdriver.Chrome("/Users/sgvin/chromedriver.exe")
url = 'https://www.wadiz.kr/web/wreward/main?keyword=&endYn=ALL&order=recent&utm_source=mkt_google&utm_medium=search&utm_campaign=2022tvc_%EC%99%80%EB%94%94%EC%A6%88%EC%84%9C%ED%8F%AC%ED%84%B0_SA&utm_term=1.%EB%B8%8C%EB%9E%9C%EB%93%9C_%ED%8E%80%EB%94%A9&utm_content=%EC%99%80%EB%94%94%EC%A6%88&gclid=Cj0KCQjwlK-WBhDjARIsAO2sErS4Q8iSiHZLMUkC78Z2K4Ldd8euJrxh5oPRvzE2pL0kX-DO_siTjj8aAitEEALw_wcB'
driver.get(url)

C:\Users\sgvin\AppData\Local\Temp/ipykernel_21876/4160910373.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("/Users/sgvin/chromedriver.exe")

In [ ]:
# 무한 스크롤을 위한 코드
import time
try:
    for i in range(1000000000000):
        button = driver.find_element_by_xpath('//*[@id="main-app"]/div[2]/div/div[3]/div[2]/div[2]/div/button') #더보기버튼 xpath
        time.sleep(0.3)
        driver.execute_script("arguments[0].click();", button)
except : 
    button = driver.find_element_by_class_name
    button.click()

In [5]:
soup1=BeautifulSoup(driver.page_source,"html.parser")

In [6]:
wadiz_title = []
wadiz_url = []
wadiz_cate = []
wadiz_mname = []

title = soup1.find_all('div',{'class':'RewardProjectCard_infoTop__3QR5w'})

for i in range(len(title)):
    wadiz_title.append(title[i].find('strong').get_text()) # 제목 수집
    wadiz_url.append(title[i].find('a')['href']) # 링크 수집
    wadiz_cate.append(title[i].find('span').get_text()) #카테고리 수집
    wadiz_mname.append(title[i].find_all('span')[1].get_text()) # 메이커명 수집

In [7]:
df1=pd.DataFrame({'title':wadiz_title,
                 'url': wadiz_url,
                 'category':wadiz_cate,
                 'manme': wadiz_mname})
df1

,title,url,category,manme
0,[폐플라스틱으로 만든 벽시계] 쓰레기로 그린 미술작품 19종,https://www.wadiz.kr/web/wcomingsoon/rwd/15310...,홈·리빙,박재범
1,[보툼메이크업핏루즈] 화장 묻는 마스크 대신 화장 안 묻는 마스크 쓰세요,/web/campaign/detail/154351?_refer_section_st=...,뷰티,빅트리플러스
2,우리아이 즐거운 목욕시간! 식물성 안심성분 쫀쫀한 버블클렌저 [뿜소],/web/campaign/detail/135538?_refer_section_st=...,뷰티,하랑세이프티
3,[내몸의 그저 빛] 진짜 효소는 근본부터 달라야 합니다. #비건 #유기농,https://www.wadiz.kr/web/wcomingsoon/rwd/14862...,푸드,주식회사 알앤쇼핑
4,[후기극찬] 힙~한 추석선물 1008시간 드라이에이징 소고기 선물세트,/web/campaign/detail/151627?_refer_section_st=...,푸드,(주)더푸드랩
...,...,...,...,...
9979,아이 발차기에 질려버린 육아빠가 만든 차량시트 보호 장치. 캥거루 킥매트,/web/campaign/detail/95603?_refer_section_st=R...,스포츠·모빌리티,생활양식
9980,"[평점 5.0앵콜]한산소곡주, 프리미엄 명절 선물세트 ""일오백 에디션""",/web/campaign/detail/122936?_refer_section_st=...,푸드,한산소곡주명인 농업회사법인 주식회사
9981,[추석전 배송] 데이터 분석으로 숙성한 돼지고기! 환상의 맛을 선물하세요,/web/campaign/detail/78094?_refer_section_st=R...,푸드,(주)딥플랜트
9982,"[3WAY캐리어]피크닉, 국내/해외여행 다양하게 커버하는 모듈 캐리어세트",/web/campaign/detail/122770?_refer_section_st=...,여행·레저,엠에이치앤코
9983,"재미와 위생을 동시에, 믿고 쓰는 1초 도마! [디팍스 본캐부캐도마]",/web/campaign/detail/122801?_refer_section_st=...,홈·리빙,제이티비씨스튜디오(주)

In [8]:
#df1.to_excel('학술크롤링_0727.xlsx')

### 각 url에 접속하여 해당 페이지 정보 긁어오기

#### 크롤링할 변수
- 새소식 : 펀딩 관리자의 글 개수
- 커뮤니티 : 참여자들의 댓글 개수
- 서포터 : 참여자 수
- 달성률 
- 금액
- 기간
- 사진개수
- 이벤트여부
- 메이커 만족도
- 메이커 서포터
- 프로젝트 좋아요 수
- 카테고리
- 년도
- 코로나 확진자 수
- 메이커
- 코로나 검사자 수

In [3]:
df1 = pd.read_excel('학술크롤링_0727.xlsx')

In [4]:
df1

,Unnamed: 0,title,url,category,manme
0,0,[폐플라스틱으로 만든 벽시계] 쓰레기로 그린 미술작품 19종,https://www.wadiz.kr/web/wcomingsoon/rwd/15310...,홈·리빙,박재범
1,1,[보툼메이크업핏루즈] 화장 묻는 마스크 대신 화장 안 묻는 마스크 쓰세요,/web/campaign/detail/154351?_refer_section_st=...,뷰티,빅트리플러스
2,2,우리아이 즐거운 목욕시간! 식물성 안심성분 쫀쫀한 버블클렌저 [뿜소],/web/campaign/detail/135538?_refer_section_st=...,뷰티,하랑세이프티
3,3,[내몸의 그저 빛] 진짜 효소는 근본부터 달라야 합니다. #비건 #유기농,https://www.wadiz.kr/web/wcomingsoon/rwd/14862...,푸드,주식회사 알앤쇼핑
4,4,[후기극찬] 힙~한 추석선물 1008시간 드라이에이징 소고기 선물세트,/web/campaign/detail/151627?_refer_section_st=...,푸드,(주)더푸드랩
...,...,...,...,...,...
9979,9979,아이 발차기에 질려버린 육아빠가 만든 차량시트 보호 장치. 캥거루 킥매트,/web/campaign/detail/95603?_refer_section_st=R...,스포츠·모빌리티,생활양식
9980,9980,"[평점 5.0앵콜]한산소곡주, 프리미엄 명절 선물세트 ""일오백 에디션""",/web/campaign/detail/122936?_refer_section_st=...,푸드,한산소곡주명인 농업회사법인 주식회사
9981,9981,[추석전 배송] 데이터 분석으로 숙성한 돼지고기! 환상의 맛을 선물하세요,/web/campaign/detail/78094?_refer_section_st=R...,푸드,(주)딥플랜트
9982,9982,"[3WAY캐리어]피크닉, 국내/해외여행 다양하게 커버하는 모듈 캐리어세트",/web/campaign/detail/122770?_refer_section_st=...,여행·레저,엠에이치앤코
9983,9983,"재미와 위생을 동시에, 믿고 쓰는 1초 도마! [디팍스 본캐부캐도마]",/web/campaign/detail/122801?_refer_section_st=...,홈·리빙,제이티비씨스튜디오(주)

In [ ]:
n_news = []
n_comment = []
n_suppoter = []
t_purpose = []
t_term = []
t_percent = []
t_amount = []
n_like = []
n_img = []

driver = webdriver.Chrome("/Users/sgvin/chromedriver.exe")

for path in df1['url']:
    path = 'https://www.wadiz.kr' + path
    driver.get(path)
    time.sleep(0.5)
    soup2=BeautifulSoup(driver.page_source,"html.parser")
    time.sleep(0.5)
    # 새소식 / 커뮤니티 댓글 / 후원자 개수: 0인 경우 오류 벌생, 전체 텍스트 수집
    n_news.append(soup2.find_all('a', {'class':'tab-link'})[3].get_text()) # 새소식 개수
    n_comment.append(soup2.find_all('a', {'class':'tab-link'})[4].get_text()) # 커뮤니티 댓글 개수
    n_suppoter.append(soup2.find_all('a', {'class':'tab-link'})[5].get_text()) # 후원자 개수

    # 목표 금액 /  펀딩 기간
    t_purpose.append(soup2.find_all('p', {'style':'color:#00b2b2;font-size:13px;line-height:20px;margin-bottom:6px;'})[0].find_all('span')[0].get_text())
    t_term.append(soup2.find_all('p', {'style':'color:#00b2b2;font-size:13px;line-height:20px;margin-bottom:6px;'})[0].find_all('span')[1].get_text())

    # 달성률
    t_percent.append(soup2.find_all('p', {'style':'margin-bottom: 16px;'})[0].find('strong').get_text())
    
    # 달성금액
    t_amount.append(soup2.find('p', {'class':'total-amount'}).get_text())

    # 좋아요 개수
    n_like.append(soup2.find('em', {'class':'cnt-like'}).get_text())

    # 본문의 이미지 개수 
    n_img.append(len(soup2.find_all('img',{'class':'fr-fic fr-dib lazyload'})))
    
    driver.execute_script("window.open();")
    driver.switch_to.window(driver.window_handles[0])
    driver.close()
    driver.switch_to.window(driver.window_handles[-1])

In [5]:
df2 = pd.DataFrame({'news':n_news,
                 'comment': n_comment,
                 'suppoter':n_suppoter,
                 'purpose': t_purpose,
                    'term':t_term,
                   'percent':t_percent,
                   'amount':t_amount,
                   'like':n_like,
                   'img':n_img})
df2

,news,comment,suppoter,pur[ose,term,percent,amount,like,img
0,새소식 2,커뮤니티 1,서포터 37,"500,000원",2022.07.26-2022.08.16,45,"228,000원 펀딩",15,27
1,새소식 1,커뮤니티 2,서포터 105,"500,000원",2022.07.27-2022.08.04,902,"4,513,000원 펀딩",56,28
2,새소식 3,커뮤니티 5,서포터 41,"500,000원",2022.07.27-2022.08.16,584,"2,922,500원 펀딩",23,68
3,새소식 6,커뮤니티 31,서포터 92,"1,000,000원",2022.07.18-2022.08.01,578,"5,785,300원 펀딩",106,66
4,새소식 1,커뮤니티,서포터 15,"500,000원",2022.07.27-2022.08.24,1025,"5,125,000원 펀딩",20,7
...,...,...,...,...,...,...,...,...,...
8061,새소식 4,커뮤니티 5,서포터 57,"1,000,000원",2021.10.20-2021.11.08,1006,"10,066,000원 펀딩",76,49
8062,새소식 3,커뮤니티 12,서포터 26,"500,000원",2021.10.20-2021.11.15,131,"655,300원 펀딩",43,42
8063,새소식 10,커뮤니티 18,서포터 247,"5,000,000원",2021.10.20-2021.10.29,216,"10,821,600원 펀딩",82,59
8064,새소식 10,커뮤니티 150,서포터 936,"5,000,000원",2021.10.20-2021.11.05,2454,"122,745,000원 펀딩",668,33
8065,새소식 14,커뮤니티 20,서포터 181,"1,000,000원",2021.10.20-2021.11.15,625,"6,253,000원 펀딩",132,48

In [6]:
#df2.to_excel('와디즈펀딩_0727ing.xlsx')

# 데이터 수집 후 전처리

In [36]:
data = pd.read_excel('와디즈펀딩_0727ing.xlsx')

In [37]:
# news, comment, suppoter에서 텍스트만 존재하는 경우 0값 입력
data['news'] = data['news'].apply(lambda x : x.split()[-1]).replace('새소식','0').astype(int)
data['comment'] = data['comment'].apply(lambda x : x.split()[-1]).replace('커뮤니티','0').astype(int)
data['suppoter'] = data['suppoter'].apply(lambda x : x.split()[-1]).replace('서포터','0').astype(int)
data

,Unnamed: 0,news,comment,suppoter,purpose,term,percent,amount,like,img
0,0,2,1,37,"500,000원",2022.07.26-2022.08.16,45,"228,000원 펀딩",15,27
1,1,1,2,105,"500,000원",2022.07.27-2022.08.04,902,"4,513,000원 펀딩",56,28
2,2,3,5,41,"500,000원",2022.07.27-2022.08.16,584,"2,922,500원 펀딩",23,68
3,3,6,31,92,"1,000,000원",2022.07.18-2022.08.01,578,"5,785,300원 펀딩",106,66
4,4,1,0,15,"500,000원",2022.07.27-2022.08.24,1025,"5,125,000원 펀딩",20,7
...,...,...,...,...,...,...,...,...,...,...
8061,8061,4,5,57,"1,000,000원",2021.10.20-2021.11.08,1006,"10,066,000원 펀딩",76,49
8062,8062,3,12,26,"500,000원",2021.10.20-2021.11.15,131,"655,300원 펀딩",43,42
8063,8063,10,18,247,"5,000,000원",2021.10.20-2021.10.29,216,"10,821,600원 펀딩",82,59
8064,8064,10,150,936,"5,000,000원",2021.10.20-2021.11.05,2454,"122,745,000원 펀딩",668,33
8065,8065,14,20,181,"1,000,000원",2021.10.20-2021.11.15,625,"6,253,000원 펀딩",132,48

In [38]:
import re

In [39]:
# purpose, amount에서 숫자만 남김
data['purpose'] = data['purpose'].apply(lambda x: int(''.join(re.findall("\d+", x))))
data['amount'] = data['amount'].apply(lambda x: int(''.join(re.findall("\d+", x))))
data

,Unnamed: 0,news,comment,suppoter,purpose,term,percent,amount,like,img
0,0,2,1,37,500000,2022.07.26-2022.08.16,45,228000,15,27
1,1,1,2,105,500000,2022.07.27-2022.08.04,902,4513000,56,28
2,2,3,5,41,500000,2022.07.27-2022.08.16,584,2922500,23,68
3,3,6,31,92,1000000,2022.07.18-2022.08.01,578,5785300,106,66
4,4,1,0,15,500000,2022.07.27-2022.08.24,1025,5125000,20,7
...,...,...,...,...,...,...,...,...,...,...
8061,8061,4,5,57,1000000,2021.10.20-2021.11.08,1006,10066000,76,49
8062,8062,3,12,26,500000,2021.10.20-2021.11.15,131,655300,43,42
8063,8063,10,18,247,5000000,2021.10.20-2021.10.29,216,10821600,82,59
8064,8064,10,150,936,5000000,2021.10.20-2021.11.05,2454,122745000,668,33
8065,8065,14,20,181,1000000,2021.10.20-2021.11.15,625,6253000,132,48

In [40]:
# 펀딩기간 -> 펀딩시작일, 펀딩마감일
data['start_date'] = data['term'].apply(lambda x : x.split('-')[0])
data['finsh_date'] = data['term'].apply(lambda x : x.split('-')[1])
data

,Unnamed: 0,news,comment,suppoter,purpose,term,percent,amount,like,img,start_date,finsh_date
0,0,2,1,37,500000,2022.07.26-2022.08.16,45,228000,15,27,2022.07.26,2022.08.16
1,1,1,2,105,500000,2022.07.27-2022.08.04,902,4513000,56,28,2022.07.27,2022.08.04
2,2,3,5,41,500000,2022.07.27-2022.08.16,584,2922500,23,68,2022.07.27,2022.08.16
3,3,6,31,92,1000000,2022.07.18-2022.08.01,578,5785300,106,66,2022.07.18,2022.08.01
4,4,1,0,15,500000,2022.07.27-2022.08.24,1025,5125000,20,7,2022.07.27,2022.08.24
...,...,...,...,...,...,...,...,...,...,...,...,...
8061,8061,4,5,57,1000000,2021.10.20-2021.11.08,1006,10066000,76,49,2021.10.20,2021.11.08
8062,8062,3,12,26,500000,2021.10.20-2021.11.15,131,655300,43,42,2021.10.20,2021.11.15
8063,8063,10,18,247,5000000,2021.10.20-2021.10.29,216,10821600,82,59,2021.10.20,2021.10.29
8064,8064,10,150,936,5000000,2021.10.20-2021.11.05,2454,122745000,668,33,2021.10.20,2021.11.05
8065,8065,14,20,181,1000000,2021.10.20-2021.11.15,625,6253000,132,48,2021.10.20,2021.11.15

In [41]:
data.drop(['Unnamed: 0','term'], axis=1,inplace=True)

In [42]:
data

,news,comment,suppoter,purpose,percent,amount,like,img,start_date,finsh_date
0,2,1,37,500000,45,228000,15,27,2022.07.26,2022.08.16
1,1,2,105,500000,902,4513000,56,28,2022.07.27,2022.08.04
2,3,5,41,500000,584,2922500,23,68,2022.07.27,2022.08.16
3,6,31,92,1000000,578,5785300,106,66,2022.07.18,2022.08.01
4,1,0,15,500000,1025,5125000,20,7,2022.07.27,2022.08.24
...,...,...,...,...,...,...,...,...,...,...
8061,4,5,57,1000000,1006,10066000,76,49,2021.10.20,2021.11.08
8062,3,12,26,500000,131,655300,43,42,2021.10.20,2021.11.15
8063,10,18,247,5000000,216,10821600,82,59,2021.10.20,2021.10.29
8064,10,150,936,5000000,2454,122745000,668,33,2021.10.20,2021.11.05
8065,14,20,181,1000000,625,6253000,132,48,2021.10.20,2021.11.15